import { addDoc, collection } from 'firebase/firestore';
import { db } from '../firebase';
import { ParentVaultItem } from '../types/firestore';

export const addItemToVault = async (
    parentId: string,
    targetChildId: string | null,
    giftData: {
        name: string;
        imageUrl: string;
        barcodeUrl: string;
    }
): Promise<string> => {
    // We add to 'parent_vault' collection.
    // The vaultId will be the document ID generated by Firestore.

    // Create a reference to the collection
    const vaultRef = collection(db, 'parent_vault');

    const newItem: Omit<ParentVaultItem, 'vaultId'> & { createdAt: any } = {
        parentId,
        targetChildId,
        gifticonData: {
            ...giftData,
            status: 'pending',
        },
        createdAt: new Date(), // Use serverTimestamp() in real app for consistency
    };

    // Add document with auto-generated ID
    const docRef = await addDoc(vaultRef, newItem);

    // We can update the doc with its own ID if needed, but Firestore ID is the key.
    // Our interface has 'vaultId', so if we fetch it, we map doc.id to vaultId.

    return docRef.id;
};
